CREATE TABLE `profile_checks` (
	`id` int AUTO_INCREMENT NOT NULL,
	`sessionId` varchar(128) NOT NULL,
	`userId` int,
	`profileCategory` enum('conservative','balanced','growth','professional') NOT NULL,
	`riskScore` int NOT NULL,
	`answers` json NOT NULL,
	`expectedReturn` varchar(32),
	`returnVsSecurity` varchar(32),
	`capitalAvailability` varchar(32),
	`investmentHorizon` varchar(32),
	`distributionPreference` varchar(32),
	`liquidityNeed` varchar(32),
	`lossToleranceMax` varchar(32),
	`lossReaction` varchar(32),
	`currentAssets` json,
	`experienceLevel` varchar(32),
	`plannedVolume` varchar(32),
	`portfolioShare` varchar(32),
	`informationNeed` varchar(32),
	`decisionProcess` varchar(32),
	`interestedBusinessAreas` json,
	`completedAt` timestamp NOT NULL DEFAULT (now()),
	`ipAddress` varchar(64),
	`userAgent` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `profile_checks_id` PRIMARY KEY(`id`)
);
