CREATE TABLE `interest_parameters` (
	`id` int AUTO_INCREMENT NOT NULL,
	`annual_interest_rate` decimal(5,2) NOT NULL DEFAULT '6.00',
	`default_interest_rate` decimal(5,2) NOT NULL DEFAULT '17.00',
	`late_payment_interest_rate` decimal(5,2) NOT NULL DEFAULT '0.00',
	`capital_gains_tax` decimal(5,2) NOT NULL DEFAULT '25.00',
	`solidarity_surcharge` decimal(5,2) NOT NULL DEFAULT '5.50',
	`church_tax` decimal(5,2) NOT NULL DEFAULT '0.00',
	`no_default_interest_for_company` boolean NOT NULL DEFAULT true,
	`enable_insolvency_hold` boolean NOT NULL DEFAULT true,
	`enable_compound_interest` boolean NOT NULL DEFAULT false,
	`round_interest_to_cent` boolean NOT NULL DEFAULT true,
	`days_per_year` int NOT NULL DEFAULT 365,
	`minimum_interest_amount` decimal(10,2) NOT NULL DEFAULT '0.01',
	`grace_period_days` int NOT NULL DEFAULT 0,
	`default_payment_frequency` varchar(20) NOT NULL DEFAULT 'monthly',
	`monthly_payment_day` int NOT NULL DEFAULT 15,
	`annual_payment_day` int NOT NULL DEFAULT 365,
	`name` varchar(255) NOT NULL DEFAULT 'Default Parameters',
	`description` text,
	`is_active` boolean NOT NULL DEFAULT true,
	`version` int NOT NULL DEFAULT 1,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`effective_from` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`effective_until` timestamp,
	CONSTRAINT `interest_parameters_id` PRIMARY KEY(`id`)
);
