CREATE TABLE `interest_calculations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`user_id` int NOT NULL,
	`principal` decimal(18,2) NOT NULL,
	`annual_rate` decimal(5,2) NOT NULL,
	`subscription_amount` decimal(18,2) NOT NULL,
	`paid_amount` decimal(18,2) NOT NULL,
	`start_date` timestamp NOT NULL,
	`periods` int NOT NULL,
	`kest_rate` decimal(5,2) NOT NULL DEFAULT '25.00',
	`solz_rate` decimal(5,2) NOT NULL DEFAULT '5.50',
	`church_tax_rate` decimal(5,2) NOT NULL DEFAULT '0.00',
	`default_rate` decimal(5,2) NOT NULL DEFAULT '17.00',
	`is_company_liability` boolean NOT NULL DEFAULT false,
	`enable_insolvency_hold` boolean NOT NULL DEFAULT false,
	`payment_frequency` varchar(20) NOT NULL,
	`basic_interest` decimal(18,2) NOT NULL,
	`kest` decimal(18,2) NOT NULL,
	`solz` decimal(18,2) NOT NULL,
	`church_tax` decimal(18,2) NOT NULL,
	`total_taxes` decimal(18,2) NOT NULL,
	`default_interest` decimal(18,2) NOT NULL,
	`applied_default_interest` decimal(18,2) NOT NULL,
	`total_interest_and_taxes` decimal(18,2) NOT NULL,
	`net_interest` decimal(18,2) NOT NULL,
	`total_payable` decimal(18,2) NOT NULL,
	`business_rules_applied` text,
	`description` text,
	`reference` varchar(255),
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `interest_calculations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `payment_schedule_items` (
	`id` int AUTO_INCREMENT NOT NULL,
	`payment_schedule_id` int NOT NULL,
	`interest_calculation_id` int NOT NULL,
	`user_id` int NOT NULL,
	`payment_number` int NOT NULL,
	`payment_date` timestamp NOT NULL,
	`principal_amount` decimal(18,2) NOT NULL,
	`interest_amount` decimal(18,2) NOT NULL,
	`tax_amount` decimal(18,2) NOT NULL,
	`default_interest_amount` decimal(18,2) NOT NULL,
	`total_payment` decimal(18,2) NOT NULL,
	`status` varchar(20) NOT NULL DEFAULT 'pending',
	`paid_at` timestamp,
	`notes` text,
	`created_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
	`updated_at` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `payment_schedule_items_id` PRIMARY KEY(`id`)
);
